import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Main from '../components/Main'
import QuadroPrincipal from '../components/QuadroPrincipal'
import RequisicaoDeId from '../components/RequisicaoDeId'
import Status from '../components/Status'

const Home: NextPage = () => {
  return (
    <div className='h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main>
        <QuadroPrincipal>
          <RequisicaoDeId />
          <Status nomeDoPokemon="Bulbassauro" HPDoPokemon={12} AtaqueDoPokemon={30} TipoDoPokemon="Folha"/>
        </QuadroPrincipal>
        <QuadroPrincipal> </QuadroPrincipal>
      </Main>
    </div>
  )
}

export default Home
