import type { NextPage } from 'next'
import Head from 'next/head'
import FotoPokemon from '../components/FotoPokemon'
import Header from '../components/Header'
import Main from '../components/Main'
import QuadroBranco from '../components/QuadroBranco'
import RequisicaoDeId from '../components/RequisicaoDeId'
import Status from '../components/Status'
import useAppData from '../dados/hook/useAppData'


const Home: NextPage = () => {
  
  const dados = useAppData()
  return (
    <div className='h-screen flex flex-col items-center'>
      
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"></link>
      </Head>
      
      <Header />
      
      <Main>
        
        <QuadroBranco>
          <RequisicaoDeId />
          <Status nomeDoPokemon={dados.nomeDoPokemon} HPDoPokemon={dados.hpDoPokemon} AtaqueDoPokemon={dados.ataqueDoPokemon} TipoDoPokemon={dados.tipoDoPokemon} />
        </QuadroBranco>
        
        <QuadroBranco>
          <FotoPokemon></FotoPokemon>
        </QuadroBranco>
      
      </Main>
      <span className="material-icons mt-6 text-5xl animate-bounce">catching_pokemon</span>
    
    </div>
  )
}

export default Home
