import type { NextPage } from 'next'
import Head from 'next/head'
import FotoPokemon from '../components/FotoPokemon'
import Header from '../components/Header'
import Main from '../components/Main'
import QuadroBranco from '../components/QuadroBranco'
import RequisicaoDeId from '../components/RequisicaoDeId'
import Status from '../components/Status'
import useAppData from '../dados/hook/useAppData'
import Image from 'next/image'
import Footer from '../components/Footer'


const Home: NextPage = () => {

  const dados = useAppData()

  const loaderImg = () => {
    return dados.foto
  }

  return (
    <div className='h-screen flex flex-col items-center'>

      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"></link>
      </Head>

      <Header />

      <Main>
        <div className='flex flex-col p-6 w-full h-full bg-orange-500 items-center justify-center
    sm:flex-col md:flex-row'>
          <QuadroBranco>
            <RequisicaoDeId />
            <Status nomeDoPokemon={dados.nome} HPDoPokemon={dados.hp} AtaqueDoPokemon={dados.ataque} TipoDoPokemon={dados.tipo} TipoDoPokemon2={dados.tipo2} />
          </QuadroBranco>

          <QuadroBranco>
            {dados.id ? <FotoPokemon><Image loader={loaderImg} src="/" alt='pokemon' width={200} height={200} quality={100} /></FotoPokemon> : null}
          </QuadroBranco>
        </div>
        <span className="material-icons mt-4 text-5xl animate-bounce">catching_pokemon</span>
      </Main>

      <Footer />

    </div>
  )
}

export default Home
